baseURL = "http://charleszinn.ca/"
languageCode = "en-us"
title = "Charles Zinn"
date = "2018-05-06"
footnoteReturnLinkContents = "↩"

[params]
  description = "Personal website of a software engineering student at the University of Waterloo."
  email = "charles.zinn@gmail.com"
