baseURL = "http://charleszinn.ca/"
languageCode = "en-us"
title = "Charles Zinn"
date = "2018-05-06"
footnoteReturnLinkContents = "↩"

[params]
  description = "Personal website of a software engineer."
  email = "charles.zinn@gmail.com"

[markup.goldmark.renderer]
unsafe = true
